<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MapView', 'doctrine');

/**
 * BaseMapView
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $pitch
 * @property integer $yaw
 * @property integer $roll
 * @property float $latitude
 * @property float $longitude
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getName()      Returns the current record's "name" value
 * @method integer getPitch()     Returns the current record's "pitch" value
 * @method integer getYaw()       Returns the current record's "yaw" value
 * @method integer getRoll()      Returns the current record's "roll" value
 * @method float   getLatitude()  Returns the current record's "latitude" value
 * @method float   getLongitude() Returns the current record's "longitude" value
 * @method MapView setId()        Sets the current record's "id" value
 * @method MapView setName()      Sets the current record's "name" value
 * @method MapView setPitch()     Sets the current record's "pitch" value
 * @method MapView setYaw()       Sets the current record's "yaw" value
 * @method MapView setRoll()      Sets the current record's "roll" value
 * @method MapView setLatitude()  Sets the current record's "latitude" value
 * @method MapView setLongitude() Sets the current record's "longitude" value
 * 
 * @package    Guff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMapView extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('map_view');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('pitch', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('yaw', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('roll', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('latitude', 'float', 15, array(
             'type' => 'float',
             'length' => 15,
             'scale' => '6',
             ));
        $this->hasColumn('longitude', 'float', 15, array(
             'type' => 'float',
             'length' => 15,
             'scale' => '6',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}