<?php

/**
 * BaseHashStat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $tag
 * @property integer $total
 * 
 * @method integer  getId()    Returns the current record's "id" value
 * @method string   getTag()   Returns the current record's "tag" value
 * @method integer  getTotal() Returns the current record's "total" value
 * @method HashStat setId()    Sets the current record's "id" value
 * @method HashStat setTag()   Sets the current record's "tag" value
 * @method HashStat setTotal() Sets the current record's "total" value
 * 
 * @package    Guff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseHashStat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hash_stat');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tag', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('total', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}