<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Post', 'doctrine');

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $ip
 * @property string $text
 * @property int $accuracy
 * @property float $latitude
 * @property float $longitude
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getIp()        Returns the current record's "ip" value
 * @method string  getText()      Returns the current record's "text" value
 * @method int     getAccuracy()  Returns the current record's "accuracy" value
 * @method float   getLatitude()  Returns the current record's "latitude" value
 * @method float   getLongitude() Returns the current record's "longitude" value
 * @method Post    setId()        Sets the current record's "id" value
 * @method Post    setIp()        Sets the current record's "ip" value
 * @method Post    setText()      Sets the current record's "text" value
 * @method Post    setAccuracy()  Sets the current record's "accuracy" value
 * @method Post    setLatitude()  Sets the current record's "latitude" value
 * @method Post    setLongitude() Sets the current record's "longitude" value
 * 
 * @package    Guff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ip', 'string', 16, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('text', 'string', 148, array(
             'type' => 'string',
             'length' => 148,
             ));
        $this->hasColumn('accuracy', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('latitude', 'float', 15, array(
             'type' => 'float',
             'length' => 15,
             'scale' => '6',
             ));
        $this->hasColumn('longitude', 'float', 15, array(
             'type' => 'float',
             'length' => 15,
             'scale' => '6',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}