<?php

/**
 * HashListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HashListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HashListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HashList');
    }
}