<?php

/**
 * HashStatsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HashStatsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HashStatsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HashStats');
    }
}