<?php

/**
 * HashStatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HashStatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HashStatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HashStat');
    }
}