<?php

/**
 * HashListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HashListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HashListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HashList');
    }
    
    public function getRecent()
   	{
   		$q = $this->createQuery()
   						->addWhere('created_at < NOW()')
   						->orderBy("created_at desc");
   		return $q->execute();
   	}
}