<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Guff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Post extends BasePost
{
    
    protected $_hashRank = 0;
    
    public function toPublicArray()
	{
	    $arr = array();
	    $arr['t'] = $this->getText();
	    $now = intval(Date('U', time()));
	    $exp = intval(Date('U', strtotime('+2 hour', strtotime($this->getCreatedAt()))));
	    $arr['e'] = ($exp-$now);
	    return $arr;
	}
	
	public function toAdminArray()
	{
	    $arr = array();
	    $arr['i'] = $this->getId();
	    $arr['t'] = $this->getText();
	    $now = intval(Date('U', time()));
	    $exp = intval(Date('U', strtotime('+2 hour', strtotime($this->getCreatedAt()))));
	    $arr['e'] = ($exp-$now);
	    $arr['lat'] = $this->getLatitude();
	    $arr['lng'] = $this->getLongitude();
	    $arr['rk'] = $this->_hashRank;
	    return $arr;
	}
	
	public function parseHashTags()
	{
	    $matches = $this->getHashTags();
        foreach ($matches as $m) {
            $h = new HashList();
            $h->tag = $m;
            $h->save();
        }

	}
	
	public function getHashTags()
	{
	    $matches = array();
	    $match = preg_match_all('/(^|\s)#(\w+)/', $this->getText(), $matches);

	    if ($match) {
	        if (count($matches)>=2 )
	        {
	            return $matches[2];
            }
        }
        return array();
	}
	
	public function getHashRanking($topHashes)
	{
	    return $this->_hashRank;
	}
	
	public function setHashRank($topHashes)
	{
	    $tags = $this->getHashTags();
	    $rank = 0;
	    foreach ($topHashes as $th) 
	    {
	        foreach ($tags as $t)
	        {
	            if ($t == $th->getTag())
	            {
	                
	                if ($th->getRank() > $rank) {
	                    $rank = $th->getRank();
	                }
	            }
	        }
	    }
	    $this->_hashRank = $rank;

	}
	
}
