# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=127.0.0.1;dbname=guff
      username: guff_admin
      password: guff_admin

dev:
  doctrine:
    param:
      dsn:      mysql:host=127.0.0.1;dbname=guff
      username: root
      password: 
      
stage:
  doctrine:
    param:
      dsn:      mysql:host=127.0.0.1;dbname=guff_stage
      username: guff_stage
      password: guff_stage

prod:
  doctrine:
    param:
      username: guff
      password: guff