HashList:
  actAs:
    Timestampable:
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    tag:
      type: string(25)


HashStat:
  actAs:
    Timestampable:
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
  

Post:
  connection: doctrine
  actAs:
    Timestampable:
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    ip:
      type: string(16)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    text: string(148)
    accuracy: int
    latitude: float(15,6)
    longitude: float(15,6)
    
MapView:
  connection: doctrine
  actAs:
    Timestampable:

      
        
    Sluggable:
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(50)
      unique: true
    pitch:
      type: integer(4)
      fixed: false
      unsigned: true
    yaw:
      type: integer(4)
      fixed: false
      unsigned: true
    roll:
      type: integer(4)
      fixed: false
      unsigned: true
    latitude: float(15,6)
    longitude: float(15,6)